version: "3.9"

services: 
  postgres-user:
    image: postgres:alpine3.20
    container_name: "zhavia_postgres_user"
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER_POSTGRESS}
      POSTGRES_PASSWORD: ${DB_PASS_POSTGRESS}
      POSTGRES_DB: ${DB_DATABASE_POSTGRESS}