version: "3.9"

services: 
  app:
    container_name: "zhavia_api_user"
    build: .
    ports:
      - "3010:3010"
    entrypoint: ["sh", "-c", "dockerize -wait tcp://postgres-user:5432 -timeout 20s pnpm install && pnpm prisma generate && pnpm prisma db push && pnpm build && pnpm run start"]
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://${DB_USER_POSTGRESS}:${DB_PASS_POSTGRESS}@postgres-user:5432/${DB_DATABASE_POSTGRESS}"
    depends_on:
      - postgres-user
    networks:
      - app-network

  postgres-user:
    image: postgres:alpine3.20
    container_name: "zhavia_postgres_user"
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER_POSTGRESS}
      POSTGRES_PASSWORD: ${DB_PASS_POSTGRESS}
      POSTGRES_DB: ${DB_DATABASE_POSTGRESS}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
